### ISSUE TITLE
"Add Selected" button does nothing

### ISSUE THREAD

**Issue by reidca** [iann0036/former2#54] opened 2020-02-07 17:44 UTC
I have entered credentials, navigated to "Migration & Transfer" then hit refresh.
Resources appear however clicking the checkbox then clicking "Add Selected" does nothing.

No errors in javascript console.

**Comment by iann0036** [comment] 2020-02-08 03:42
Hi @reidca,

Thanks for raising. Could you let me know which of the following services has the issue?

* Database Migration Service
* Transfer
* DataSync

And if there is anything else special about these specific resources, that'd be great.

**Comment by reidca** [comment] 2020-02-10 10:42
It's the Transfer server under "Migration & Transfer". I have tried it again to ensure it was not a temporary issue.

Steps to reproduce:

1. Open Former 2 in Chrome (I have also tried it in Firefox)
2. Go to setup and enter Access Key and Secret Key
3. Choose "Enable Related Resources"
4. Go to Migration and Transfer - Transfer
5. Change region to eu-west-1
6. Click the refresh icon
7. Put a tick in the checkbox under the "Servers" tab
8. Click Add Selected - nothing happens

Thanks

Carl

**Comment by iann0036** [comment] 2020-02-10 11:50
Hey @reidca,

Thanks for confirming those details, they were very helpful in me finding what I believe is the cause of this issue.

I believe the issue was due to the column named "State" which conflicted internally with the row checked state the table tracks on. I made a non-conflicting identifier for this column now so hopefully this should be the fix.

Could you give it a shot and let me know if this fixes the issue for you?

**Comment by reidca** [comment] 2020-02-10 14:33
That's fixed it - thank you.

As an observation, it would be good to get the IAM policies and roles added to the template as related resources if that's possible. 

To me the creation of a transfer server, the users as well as the roles are all one concern and therefore should be in the same template.

**Comment by iann0036** [comment] 2020-02-10 22:04
Thanks for confirming.

On related resources, if the option is checked in the Settings _and_ you do an account scan beforehand, related resources may be suggested. This works in some places better than others (VPC is pretty good for this, haven't tested extensively elsewhere).

The account scan is required to get the details of all resources in the account as this isn't necessarily the case when loading a single view.

Give it a try and raise another issue if you find specific behaviour that you believe should be fixed, feel free to raise it.

**Closed by iann0036** 2020-02-10 22:04 UTC
Labels: bug
