### ISSUE TITLE
elbv2 TargetGroupName is being left off on output

### ISSUE THREAD

**Issue by tmblue** [iann0036/former2#23] opened 2019-10-25 18:30 UTC
elbv2 loadbalancer to elb2 listener and elb2 listener rules are clear,  But there is absolutely zero connection to the elbv2 target groups.

Raw has the data, but no other format is providing the TargetGroupName

The TargetGroupName is being omitted on the output, this must be there, or there is no way to create a functioning template based on the data, as there is no clear path to the required TargetGroupName, the name must be part of the template output

And actually TargetGroupName is not valid, so it should be just Name, but it should be pushed to the template options.

What is available:

    TargetGroupArn: arn:aws:elasticloadbalancing:us-west-1:SECURED:targetgroup/targetgroupname/8f17490f4a037da8
    **TargetGroupName: dev03-3048**
    Protocol: HTTP
    Port: 3048
    VpcId: SECURED
    HealthCheckProtocol: HTTP
    HealthCheckPort: traffic-port
    HealthCheckEnabled: true
    HealthCheckIntervalSeconds: 5
    HealthCheckTimeoutSeconds: 2
    HealthyThresholdCount: 2
    UnhealthyThresholdCount: 2
    HealthCheckPath: /status.html
    Matcher:
        HttpCode: 200
    LoadBalancerArns:
        - arn:aws:elasticloadbalancing:us-west-1:SECURED:loadbalancer/app/loadbalancername/e874f0d809d66790
    TargetType: instance

What is being provided:

        "elbvtargetgroup": {
            "Type": "AWS::ElasticLoadBalancingV2::TargetGroup",
            "Properties": {
                "HealthCheckIntervalSeconds": 30,
                "HealthCheckPath": "/status.html",
                "Port": 80,
                "Protocol": "HTTP",
                "HealthCheckPort": "traffic-port",
                "HealthCheckProtocol": "HTTP",
                "HealthCheckTimeoutSeconds": 5,
                "UnhealthyThresholdCount": 2,
                "TargetType": "instance",
                "Matcher": {
                    "HttpCode": "200"
                },
                "HealthyThresholdCount": 2,
                "VpcId": "vpc-SECURED
            }
        },

RAW (has it, so the template formats must be updated to also grab the Name)
   "id": "adm-dev-dev05",
        "type": "elbv2.targetgroup",
        "data": {
            "TargetGroupArn": "arn:aws:elasticloadbalancing:us-west-1:SECURED:targetgroup/adm-dev-dev05/8cfa129b71b647da",
            "TargetGroupName": "adm-dev-dev05", <--Should be "Name":
            "Protocol": "HTTP",
            "Port": 80,
            "VpcId": "vpc-c02860a5",
            "HealthCheckProtocol": "HTTP",
            "HealthCheckPort": "traffic-port",
            "HealthCheckEnabled": true,
            "HealthCheckIntervalSeconds": 30,
            "HealthCheckTimeoutSeconds": 5,
            "HealthyThresholdCount": 5,
            "UnhealthyThresholdCount": 2,
            "HealthCheckPath": "/status.html",
            "Matcher": {
                "HttpCode": "200"
            },
            "LoadBalancerArns": [
                "arn:aws:elasticloadbalancing:us-west-1:SECURED:loadbalancer/app/loadbalancer/e874f0d809d66790"
            ],
            "TargetType": "instance"
        },
        "region": "us-west-1"
    },

**Comment by iann0036** [comment] 2019-10-26 02:38
Thanks for raising!

The fix for this should now be available. Feel free to reopen if the issue is still occurring.

**Closed by iann0036** 2019-10-26 02:38 UTC
Labels: bug
